version: "3.9"
services:
   database:
      container_name: docker-netword-postgres
      image: postgres
      ports:
         - "4321:5432"
      environment:
         POSTGRES_USER: "root"
         POSTGRES_PASSWORD: "password"
      volumes:
         - type: volume
           source: random-db
           target: /var/lib/postgresql/data

   app:
      container_name: docker-network-server
      build: .
      ports:
         - "3000:3000"
      depends_on:
         - database
      env_file:
         - ./.env

volumes:
   random-db:
      external: true
